name: mechapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  #sdk: ">=2.2.2 <3.0.0"
  sdk: ">=2.8.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^0.1.2
  image_picker:
  google_maps_flutter: ^0.5.24+1
  firebase_database:
  firebase_storage:
  intent: ^1.1.0
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.1+2
  cloud_firestore:
  url_launcher:
  cached_network_image:
  geolocator: ^6.1.12
  carousel_slider: ^2.3.1
  rave_flutter: ^0.0.9-alpha+2
  google_geocoding: ^0.1.4
  intl:
  loading_overlay:
  google_maps_webservice:
  smooth_star_rating:
  floor: ^0.12.0
  flutter_google_places: ^0.2.5
  flutter_staggered_grid_view: ^0.3.2
  flutter_svg: ^0.18.1
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.12.0
  build_runner: ^1.7.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
